---
- name: look up user-defined secret
  set_fact:
    usrsecret: "{{ lookup('vars', varname) | default('') }}"

- name: check existing secret-file
  register: statres
  stat:
    path: "{{ filepath }}"

- name: populate secret-file
  when: not statres.stat.exists or (statres.stat.size == 0)
  block:
  - name: generate new secret
    set_fact:
      secret: "{{ usrsecret | default(lookup('password', '/dev/null length=32 chars=ascii_uppercase,digits'), true) }}"
  - name: store new secret
    copy:
      dest: "{{ filepath }}"
      content: "{{ secret }}"
      mode: o=,g=,u=rw

- name: look up current secret
  when: statres.stat.exists
  block:
  - name: read current secret-file
    command: "cat '{{ filepath }}'"
    register: catres
  - name: set current secret
    set_fact:
      secret: "{{ catres.stdout }}"

- name: compare user-defined secret
  when: usrsecret | length > 0
  assert:
    that: secret == usrsecret
    fail_msg: Changing existing secret is currently not supported!

- name: update secret-variable
  set_fact:
    "{{ varname }}": "{{ secret }}"
