---
- name: download pre-built ui
  when: not operator_enabled
  get_url:
    url: "{{ ui_artifact_url }}"
    dest: "{{ host_ui_artifact_file }}"
    force: "{{ eaas_component_ui in eaas_update_components }}"
    headers:
      PRIVATE-TOKEN: "{{ ui_private_token  | default(omit) }}"

- name: extract pre-built ui
  when: not operator_enabled
  unarchive:
    src: "{{ host_ui_artifact_file }}"
    dest: "{{ host_ui_install_dir }}"
    remote_src: yes

- name: prepare admin-ui config
  when: ui_enable_admin_ui or ui_landing_page
  template:
    dest: "{{ host_eaas_config_dir }}/admin-ui.json"
    src: "ui/admin-ui-config.json.j2"
    mode: "u=rw,g=r,o=r"
