---
- name: update service facts
  service_facts:
  no_log: true

- set_fact:
    _eaas_service: "{{host_eaas_service_name}}.service"

- name: "ensure eaas-server is {{ state }}"
  when: '_eaas_service in ansible_facts.services'
  become: yes
  service:
    name: "{{host_eaas_service_name}}.service"
    state: "{{ state }}"
