---
host_eaas_home: "{{ host.eaas_home }}"
host_build_dir: "{{ host.build_dir }}"
host_eaas_config_dir: "{{ host_eaas_home }}/config"
host_eaas_config_parts_dir: "{{ host_eaas_config_dir }}/eaas-config.d"
host_eaas_config_nginx_dir: "{{ host_eaas_config_dir }}/nginx"
host_eaas_config_nghttpx_dir: "{{ host_eaas_config_dir }}/nghttpx"
host_ui_artifact_file: "{{ host_eaas_tmp }}/eaas-ui.zip"
host_ui_install_dir: "{{ host_eaas_home }}/eaas-ui"
host_eaas_service_name: "{{host.eaas_service_name | default('eaas') }}"
host_db_upgrade_repo_dir: "{{ host_eaas_tmp }}/db-upgrade"
host_tmp_storage: "{{host.temp_storage | default( host_eaas_home + '/tmp-storage') }}"
host_portal_home: "{{ host_eaas_home }}/portal"

docker_image: "{{ docker.image }}"
docker_proxy_image: "{{ docker.proxy_image | default('eaas/eaas-proxy')}}"
docker_compose_file_version: "{{docker.compose_file_version | default('3.7')}}"
docker_custom_volumes: "{{ docker.volumes | default('') }}"
docker_ssl_enabled: "{{ docker.ssl is defined and docker.ssl.enabled }}"
docker_ssl_certificate: "{% if docker_ssl_enabled %}{{ docker.ssl.certificate | default('') }}{% endif %}"
docker_ssl_private_key: "{% if docker_ssl_enabled %}{{ docker.ssl.private_key | default('') }}{% endif %}"
docker_default_proxy_port: 80
docker_default_proxy_ssl_port: 443
__portal_proxy_nossl_port: "{{ portal.docker_ports.proxy | default(docker_default_proxy_port) }}"
__portal_proxy_ssl_port: "{{ portal.docker_ports.proxy_ssl | default(docker_default_proxy_ssl_port) }}"
__portal_proxy_port: "{% if docker_ssl_enabled %}{{ __portal_proxy_ssl_port }}{% else %}{{ __portal_proxy_nossl_port }}{% endif %}"
__docker_default_port: "{% if docker_ssl_enabled %}{{ docker_default_proxy_ssl_port }}{% else %}{{ docker_default_proxy_port }}{% endif %}"
docker_port: "{% if portal is defined %}{{ __portal_proxy_port }}{% else %}{{ docker.port | default(__docker_default_port) }}{% endif %}"
docker_internal_port: "{% if portal is defined %}8080{% elif docker_ssl_enabled %}443{% else %}8090{% endif %}"
docker_port_mapping: "{{ docker_port }}:{{ docker_internal_port }}"
docker_network_ports: "{{docker.network_ports | default('')}}"
docker_objects_volume: "{{ docker.objects_volume | default('') }}"
docker_export_volume: "{{ docker.export_volume | default('') }}"
docker_image_archive_volume: "{{ docker.image_archive_volume | default('') }}"
docker_import_volume: "{{ docker.import_volume | default('') }}"
docker_disable_tmp_volume: "{{docker.disable_tmp_volume | default(false) }}"

# A list of components to update
eaas_update_components: ''
eaas_component_ui: 'ui'
eaas_component_ear: 'ear'
eaas_component_docker_image: 'docker-image'

eaas_deployment_mode: 'all'
eaas_hostname: "{{ eaas.public_fqdn | default(ansible_host) }}"
eaas_frontend_protocol: "{{eaas.frontend_protocol | default('http://') }}"
eaas_public_port: "{{ eaas.public_port | default(docker_port) }}"
eaas_protocol: "{% if docker_ssl_enabled %}https://{% else %}{{ eaas.frontend_protocol | default('http://') }}{% endif %}"
eaas_http_proxy: "{{ eaas.http_proxy | default('') }}"
eaas_http_cache_path: "{{ eaas.http_cache_path | default('') }}"
eaas_http_proxy_cache_size: "{{ eaas.http_proxy_cache_size | default('') }}"
eaas_software_archive_id: "{{ eaas.software_archive_id | default('default') }}"
eaas_object_archive_id: "{{ eaas.object_archive_id | default('default') }}"
eaas_enable_new_image_archive: "{{ eaas.enable_new_image_archive | default(true) }}"
eaas_enable_oaipmh_provider: "{{ eaas.enable_oaipmh_provider | default(false) }}"
eaas_enable_oaipmh_harvester: "{{ eaas.enable_oaipmh_harvester | default(true) }}"
eaas_enable_handlenet: "{{ eaas.enable_handlenet | default(false) }}"
eaas_cluster_api_access_token: "{{ eaas.cluster_api_access_token | default('') }}"
eaas_dns: "{{ eaas.dns | default('') }}"
eaas_db_upgrade: "{{ eaas.db_upgrade | default(false) }}"
eaas_db_upgrade_repo: "https://gitlab.com/emulation-as-a-service/mongodb-upgrade.git/"
eaas_custom_files: "{{ eaas.files | default([]) }}"
eaas_enable_emulator_containers: "{{eaas.enable_emulator_containers | default(true) }}"
eaas_enable_snapshots: "{{ eaas.enable_snapshots | default(false) }}"

eaas_enable_backend_auth: "{{ eaas.enable_backend_auth | default(false) }}"
eaas_api_secret: "{{ eaas.api_secret | default('') }}"

eaas_enable_user_auth: "{{ eaas.enable_user_auth | default(false) }}"
eaas_auth_single_user: "{{ eaas.single_user_mode | default(true) }}"
eaas_auth_audience: "{{ eaas.auth_audience | default('eaas') }}"

eaas_enable_webrtc: "{{ eaas.enable_webrtc | default(false) }}"
eaas_user_archive_prefix: "{{ eaas.user_archive_prefix | default('user_archive')}}"
eaas_default_archive: "{{ eaas.default_archive | default('default')}}"

keycloak_enabled: "{{ keycloak.enabled | default(false) }}"
keycloak_admin_user: "{{ keycloak.admin_user | default('admin') }}"
keycloak_admin_password: "{{ keycloak.admin_password | default('') }}"
keycloak_frontend_url: "{{ keycloak.frontend_url | default('') }}"
keycloak_theme_repo: "{{ keycloak.theme_repo | default('') }}"
keycloak_enable_user_groups: "{{ keycloak.enable_user_groups | default(false) }}"
keycloak_client_id: "{{keycloak.client_id | default('eaas') }}"

coturn_enabled: "{{ coturn.enabled | default(false) }}"

ui_http_auth: "{{ ui.http_auth | default('') }}"
ui_enable_screenshooter: "{{ ui.enable_screenshooter | default(true) }}"
ui_enable_containers: "{{ ui.enable_containers | default(false) }}"
ui_enable_object_environments: "{{ ui.enable_object_environments | default(true) }}"
ui_enable_objects: "{{ ui.enable_objects | default(true) }}"
ui_enable_software: "{{ ui.enable_software | default(true) }}"
ui_enable_emulators: "{{ ui.enable_emulators | default(true) }}"
ui_enable_object_upload: "{{ ui.enable_object_upload | default(true) }}"
ui_enable_network: "{{ ui.enable_network | default(true) }}"
ui_enable_network_sessions: "{{ ui.enable_network_sessions | default(false) }}"
ui_enable_oaipmh: "{{ ui.enable_oaipmh | default(true) }}"
ui_enable_advanced: "{{ ui.enable_advanced | default(false) }}"
ui_enable_admin_ui: "{{ ui.enable_admin_ui | default(true) }}"
ui_enable_user_ui: "{{ ui.enable_user_ui | default(false) }}"
ui_enable_standalone: "{{ui.enable_standalone | default(false) }}"
ui_landing_page: "{{ ui.landing_page | default(false) }}"
ui_help_url: "{{ ui.help_url | default('') }}"
