---
host_eaas_home: "{{ host.eaas_home }}"
host_build_dir: "{{ host.build_dir }}"
host_eaas_config_dir: "{{ host_eaas_home }}/config"
host_eaas_config_parts_dir: "{{ host_eaas_config_dir }}/eaas-config.d"
host_ui_artifact_file: "{{ host_eaas_tmp }}/eaas-ui.zip"
host_ui_install_dir: "{{ host_eaas_home }}/eaas-ui"
host_eaas_service_name: "{{host.eaas_service_name | default('eaas') }}"

docker_image: "{{ docker.image }}"
docker_proxy_image: "{{ docker.proxy_image | default('eaas/eaas-proxy')}}"
docker_custom_image: eaas-custom
docker_compose_file_version: "{{docker.compose_file_version | default('3.1')}}"
docker_custom_volumes: "{{ docker.volumes | default('') }}"
docker_ssl_enabled: "{{ docker.ssl is defined and docker.ssl.enabled }}"
docker_ssl_certificate: "{% if docker_ssl_enabled %}{{ docker.ssl.certificate | default('') }}{% endif %}"
docker_ssl_private_key: "{% if docker_ssl_enabled %}{{ docker.ssl.private_key | default('') }}{% endif %}"
docker_port: "{{ docker.port }}"
docker_port_mapping: "{% if docker_ssl_enabled %}{{ docker_port }}:443{% else %}{{ docker_port }}:8090{% endif %}"
docker_network_ports: "{{docker.network_ports | default('')}}"
docker_objects_volume: "{{ docker.objects_volume | default('') }}"
docker_export_volume: "{{ docker.export_volume | default('') }}"
docker_image_archive_volume: "{{ docker.image_archive_volume | default('') }}"
docker_import_volume: "{{ docker.import_volume | default('') }}"

# A list of components to update
eaas_update_components: ''
eaas_component_ui: 'ui'
eaas_component_ear: 'ear'
eaas_component_docker_image: 'docker-image'

eaas_deployment_mode: 'all'
eaas_hostname: "{{ ansible_host }}"
eaas_protocol: "{% if docker_ssl_enabled %}https://{% else %}http://{% endif %}"
eaas_http_proxy: "{{ eaas.http_proxy | default('') }}"
eaas_http_cache_path: "{{ eaas.http_cache_path | default('') }}"
eaas_http_proxy_cache_size: "{{ eaas.http_proxy_cache_size | default('') }}"
eaas_software_archive_id: "{{ eaas.software_archive_id | default('default') }}"
eaas_object_archive_id: "{{ eaas.object_archive_id | default('default') }}"
eaas_enable_new_image_archive: "{{ eaas.enable_new_image_archive | default(true) }}"
eaas_enable_oaipmh_provider: "{{ eaas.enable_oaipmh_provider }}"
eaas_enable_oaipmh_harvester: "{{ eaas.enable_oaipmh_harvester | default(true) }}"
eaas_enable_handlenet: "{{ eaas.enable_handlenet | default(false) }}"
eaas_cluster_api_access_token: "{{ eaas.cluster_api_access_token | default('') }}"
eaas_dns_credentials: "{{ eaas.dns_credentials | default('') }}"
eaas_custom_files: "{{ eaas.files | default([]) }}"
eaas_enable_emulator_containers: "{{eaas.enable_emulator_containers | default(true) }}"
eaas_enable_snapshots: "{{ eaas.enable_snapshots | default(false) }}"

ui_http_auth: "{{ ui.http_auth | default('') }}"
ui_enable_screenshooter: "{{ ui.enable_screenshooter | default(true) }}"
ui_enable_containers: "{{ ui.enable_containers | default(false) }}"
ui_enable_object_environments: "{{ ui.enable_object_environments | default(true) }}"
ui_enable_objects: "{{ ui.enable_objects | default(true) }}"
ui_enable_software: "{{ ui.enable_software | default(true) }}"
ui_enable_emulators: "{{ ui.enable_emulators | default(true) }}"
ui_enable_object_upload: "{{ ui.enable_object_upload | default(true) }}"
ui_enable_network: "{{ ui.enable_network | default(true) }}"
ui_enable_network_sessions: "{{ ui.enable_network_sessions | default(false) }}"
ui_enable_oaipmh: "{{ ui.enable_oaipmh | default(true) }}"
ui_enable_advanced: "{{ ui.enable_advanced | default(false) }}"
ui_enable_admin_ui: "{{ ui.enable_admin_ui | default(true) }}"
ui_enable_user_ui: "{{ ui.enable_user_ui | default(false) }}"
ui_landing_page: "{{ ui.landing_page | default(false) }}"
ui_help_url: "{{ ui.help_url | default('') }}"
