---
host_eaas_home: "{{ host.eaas_home }}"
host_eaas_config_dir: "{{ host_eaas_home }}/config"
host_eaas_config_parts_dir: "{{ host_eaas_config_dir }}/eaas-config.d"
host_eaas_config_nginx_dir: "{{ host_eaas_config_dir }}/nginx"
host_eaas_config_nghttpx_dir: "{{ host_eaas_config_dir }}/nghttpx"
host_eaas_config_objectarchive_dir: "{{ host_eaas_config_dir }}/object-archives"
host_ui_artifact_file: "{{ host_eaas_tmp }}/eaas-ui.zip"
host_ui_install_dir: "{{ host_eaas_home }}/eaas-ui"
host_eaas_service_name: "{{host.eaas_service_name | default('eaas') }}"
host_db_upgrade_repo_dir: "{{ host_eaas_tmp }}/db-upgrade"
host_tmp_storage: "{{host.temp_storage | default( host_eaas_home + '/tmp-storage') }}"
host_eaasi_ui_home: "{{ host_eaas_home }}/eaasi-ui"

docker_image: "{{ docker.image }}"
docker_proxy_image: "{{ docker.proxy_image | default('eaas/eaas-proxy')}}"
docker_compose_file_version: "{{docker.compose_file_version | default('3.7')}}"
docker_custom_volumes: "{{ docker.volumes | default('') }}"
docker_ssl_enabled: "{{ docker.ssl is defined and docker.ssl.enabled }}"
docker_ssl_terminated: "{{ docker.ssl.terminated | default(false) }}"
docker_ssl_certificate: "{% if docker_ssl_enabled %}{{ docker.ssl.certificate | default('') }}{% endif %}"
docker_ssl_private_key: "{% if docker_ssl_enabled %}{{ docker.ssl.private_key | default('') }}{% endif %}"
docker_default_proxy_port: 80
docker_default_proxy_ssl_port: 443
__eaasi_ui_proxy_nossl_port: "{{ eaasi_ui.docker_ports.proxy | default(docker_default_proxy_port) }}"
__eaasi_ui_proxy_ssl_port: "{{ eaasi_ui.docker_ports.proxy_ssl | default(docker_default_proxy_ssl_port) }}"
__eaasi_ui_proxy_port: "{% if docker_ssl_enabled %}{{ __eaasi_ui_proxy_ssl_port }}{% else %}{{ __eaasi_ui_proxy_nossl_port }}{% endif %}"
__docker_default_port: "{% if docker_ssl_enabled %}{{ docker_default_proxy_ssl_port }}{% else %}{{ docker_default_proxy_port }}{% endif %}"
docker_port: "{% if eaasi_ui is defined %}{{ __eaasi_ui_proxy_port }}{% else %}{{ docker.port | default(__docker_default_port) }}{% endif %}"
docker_nossl_port: "{% if eaasi_ui is defined %}{{ __eaasi_ui_proxy_nossl_port }}{% else %}{{ docker_default_proxy_port }}{% endif %}"
docker_internal_port: "{% if eaasi_ui is defined %}8080{% elif docker_ssl_enabled %}443{% else %}80{% endif %}"
docker_port_mapping: "{{ docker_port }}:{{ docker_internal_port }}"
docker_network_ports: "{{docker.network_ports | default('')}}"
docker_objects_volume: "{{ docker.objects_volume | default('') }}"
docker_export_volume: "{{ docker.export_volume | default('') }}"
docker_image_archive_volume: "{{ docker.image_archive_volume | default('') }}"
docker_import_volume: "{{ docker.import_volume | default('') }}"
docker_disable_tmp_volume: "{{docker.disable_tmp_volume | default(false) }}"

# A list of components to update
eaas_update_components: ''
eaas_component_ui: 'ui'
eaas_component_ear: 'ear'
eaas_component_docker_image: 'docker-image'
eaas_component_server_data: 'server-data'

eaas_deployment_mode: 'all'
eaas_devmode_enabled: "{{ eaas.enable_devmode | default(false) }}"
eaas_hostname: "{{ eaas.public_fqdn | default(ansible_host) }}"
eaas_frontend_protocol: "{{eaas.frontend_protocol | default('http://') }}"
eaas_public_port: "{{ eaas.public_port | default(docker_port) }}"
eaas_nossl_port: "{{ eaas.nossl_port | default(docker_nossl_port) }}"
eaas_protocol: "{% if docker_ssl_enabled %}https://{% else %}{{ eaas.frontend_protocol | default('http://') }}{% endif %}"
eaas_base_url_port: "{{ '' if (eaas_public_port|int in [80, 443]) else (':' + eaas_public_port) }}"
eaas_base_url: "{{ eaas_protocol + eaas_hostname + eaas_base_url_port }}"
eaas_http_proxy: "{{ eaas.http_proxy | default('') }}"
eaas_http_cache_path: "{{ eaas.http_cache_path | default('') }}"
eaas_http_proxy_cache_size: "{{ eaas.http_proxy_cache_size | default('') }}"
eaas_software_archive_id: "{{ eaas.software_archive_id | default('default') }}"
eaas_object_archive_id: "{{ eaas.object_archive_id | default('default') }}"
eaas_enable_new_image_archive: "{{ eaas.enable_new_image_archive | default(true) }}"
eaas_enable_oaipmh_provider: "{{ eaas.enable_oaipmh_provider | default(false) }}"
eaas_enable_oaipmh_harvester: "{{ eaas.enable_oaipmh_harvester | default(true) }}"
eaas_enable_handlenet: "{{ eaas.enable_handlenet | default(false) }}"
eaas_cluster_api_access_token: "{{ eaas.cluster_api_access_token | default('') }}"
eaas_dns: "{{ eaas.dns | default('') }}"
eaas_db_upgrade: "{{ eaas.db_upgrade | default(false) }}"
eaas_db_upgrade_repo: "https://gitlab.com/emulation-as-a-service/mongodb-upgrade.git/"
eaas_custom_files: "{{ eaas.files | default([]) }}"
eaas_enable_emulator_containers: "{{eaas.enable_emulator_containers | default(true) }}"
eaas_enable_snapshots: "{{ eaas.enable_snapshots | default(false) }}"
eaas_standalone: "{{ eaas.standalone | default(false) }}"
eaas_enable_backend_auth: "{{ eaas.enable_backend_auth | default(false) }}"
eaas_secrets_dir: "{{ host_eaas_config_dir }}/secrets"
eaas_api_secret: "{{ eaas.api_secret | default('') }}"
eaas_internal_api_secret: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') | upper }}"
eaas_enable_user_auth: "{{ eaas.enable_user_auth | default(false) }}"
eaas_auth_single_user: "{{ eaas.single_user_mode | default(true) }}"
eaas_auth_audience: "{{ eaas.auth_audience | default('eaas') }}"
eaas_enable_webrtc: "{{ eaas.enable_webrtc | default(false) }}"
eaas_user_archive_enabled: "{{ eaas.user_archive_enabled | default(true)}}"
eaas_user_archive_prefix: "{{ eaas.user_archive_prefix | default('user-')}}"
eaas_default_archive: "{{ eaas.default_archive | default('default')}}"
eaas_imagearchive_storage: "{{ eaas.imagearchive.storage | default([]) }}"
eaas_objectarchive_backends: "{{ eaas.objectarchive.backends | default(eaas_objectarchive_default_backends) }}"
eaas_ssl_basedir: "{{ host_eaas_home }}/certificates"
eaas_ssl_certificate: "{{ eaas_ssl_basedir }}/server.crt"
eaas_ssl_private_key: "{{ eaas_ssl_basedir }}/server.key"
eaas_hooks_dir: "{{ host_eaas_home }}/hooks"
eaas_hooks_runner: "{{ eaas_hooks_dir }}/runner.sh"

eaas_objectarchive_default_backends:
- type: "S3"
  name: "zero conf"
  default_archive: true
  endpoint: "http://minio:9000"
  access_key: "{{ minio_user_key }}"
  secret_key: "{{ minio_user_secret }}"
  bucket: "object-archive"

# backend's endpoints
eaas_endpoints:
- 'blobstore'
- 'dig-pub-sharing'
- 'eaas'
- 'emil'
- 'emucomp'
- 'environment-proposer'
- 'image-archive/v2'
- 'imagearchive'
- 'imagebuilder'
- 'imageclassifier'
- 'imageproposer'
- 'oaipmh'
- 'objectarchive'
- 'softwarearchive'

# options passed directly to the application-server
eaas_server_options: "{{ eaas_common_server_options + (eaas.server_options | default([])) }}"
eaas_common_server_options:
- "-Dresteasy.preferJacksonOverJsonB=true"
- "-Dsun.net.client.defaultConnectTimeout=600000"
- "-Dsun.net.client.defaultReadTimeout=600000"

# user-defined list of migrations
eaas_migrations: "{{ eaas.migrations | default([]) }}"

minio_enabled: "{{ minio.enabled | default(true) }}"
minio_version: "{{ minio.version | default('latest') }}"
minio_key: "{{ minio.key | default('admin') }}"
minio_secret: "{{ minio.secret | default('') }}"
minio_user_key: "{{ minio.user_key | default ('eaas') }}"
minio_user_secret: "{{ minio.user_secret | default('') }}"
minio_data_path: "{{ minio.data_path | default(host_eaas_home + '/minio')}}"
minio_secrets_dir: "{{ host_eaas_config_dir }}/minio/secrets"
minio_policies_dir: "{{ host_eaas_config_dir }}/minio/policies"
minio_imagearchive_policy_file: "{{ minio_policies_dir }}/image-archive.json"

keycloak_enabled: "{{ keycloak.enabled | default(false) }}"
keycloak_version: "{{ keycloak.version | default('latest') }}"
keycloak_admin_user: "{{ keycloak.admin_user | default('admin') }}"
keycloak_admin_role_label: "{{ keycloak.admin_role_labe | default('eaas-admin') }}"
keycloak_user_role_label: "{{ keycloak.user_role_label | default('eaas-user') }}"
keycloak_admin_password: "{{ keycloak.admin_password | default('') }}"
keycloak_frontend_url: "{{ keycloak.frontend_url | default(eaas_base_url + '/auth') }}"
keycloak_enable_user_groups: "{{ keycloak.enable_user_groups | default(false) }}"
keycloak_client_id: "{{keycloak.client_id | default('eaas') }}"
keycloak_config_dir: "{{ host_eaas_config_dir }}/keycloak"
keycloak_secrets_dir: "{{ keycloak_config_dir }}/secrets"
keycloak_runtime_dir: "{{ host_eaas_home }}/keycloak"
keycloak_data_dir: "{{ keycloak_runtime_dir }}/data"
keycloak_defaults_file: "{{ keycloak_config_dir }}/defaults.json"
keycloak_theme_enabled: "{{ keycloak.theme is defined }}"
keycloak_theme_name: "{{ keycloak.theme.name | default('') }}"
keycloak_theme_file: "{{ keycloak_runtime_dir }}/eaasi-theme.jar"
keycloak_redirect_uris: "{{ keycloak.redirect_uris | default([]) }}"

coturn_enabled: "{{ coturn.enabled | default(false) }}"

# add aliasing for user-facing ui configs,
# so that 'ui' or 'demo_ui' can be used
ui: "{{ demo_ui }}"

ui_http_auth: "{{ ui.http_auth | default('') }}"
ui_enable_screenshooter: "{{ ui.enable_screenshooter | default(true) }}"
ui_enable_containers: "{{ ui.enable_containers | default(false) }}"
ui_enable_object_environments: "{{ ui.enable_object_environments | default(true) }}"
ui_enable_objects: "{{ ui.enable_objects | default(true) }}"
ui_enable_software: "{{ ui.enable_software | default(true) }}"
ui_enable_emulators: "{{ ui.enable_emulators | default(true) }}"
ui_enable_object_upload: "{{ ui.enable_object_upload | default(true) }}"
ui_enable_network: "{{ ui.enable_network | default(true) }}"
ui_enable_network_sessions: "{{ ui.enable_network_sessions | default(false) }}"
ui_enable_oaipmh: "{{ ui.enable_oaipmh | default(true) }}"
ui_enable_advanced: "{{ ui.enable_advanced | default(false) }}"
ui_enable_admin_ui: "{{ ui.enable_admin_ui | default(true) }}"
ui_enable_user_ui: "{{ ui.enable_user_ui | default(false) }}"
ui_enable_standalone: "{{ui.enable_standalone | default(false) }}"
ui_landing_page: "{{ ui.landing_page | default(false) }}"
ui_help_url: "{{ ui.help_url | default('') }}"
ui_frontend_url: "{{ ui.frontend_url | default('')}}"

operator_enabled: "{{ operator is defined | default(false) }}"
operator_image: "{{ operator.image | default('registry.gitlab.com/emulation-as-a-service/eaas-operator') }}"
operator_release_channel: "{{ operator.release.channel }}"
operator_release_version: "{{ operator.release.version }}"
operator_channels: "{{ operator.channels }}"
operator_credentials: "{{ operator.credentials | default('') }}"

# resolver options
resolver_cache_enabled: "{{ (resolver.cache.enabled | default(false)) or eaas_deployment_mode == 'emucomp' }}"
resolver_cache_kind: "{{ resolver.cache.kind | default('slice') }}"
resolver_cache_capacity: "{{ resolver.cache.capacity | default('20g') }}"
resolver_cache_expiration_time: "{{ resolver.cache.expiration_time | default('14d') }}"
resolver_cache_slice_size: "{{ resolver.cache.slice_size | default('1m') }}"

# autorun-scripts
eaas_autorun_scripts_file: "{{ host_eaas_tmp }}/eaas-autorun-scripts.zip"
eaas_autorun_scripts_tmpdir: "{{ host_eaas_tmp }}/eaas-autorun-scripts"
eaas_autorun_scripts_install_dir: "{{ host_eaas_home }}/server-data/autorun-scripts"
eaas_autorun_scripts_enabled: "{{ eaas.autorun_scripts.enabled | default(false) }}"
eaas_autorun_scripts_url: "{{ eaas.autorun_scripts.source }}"

# image-generalization-patches
eaas_generalization_patches_file: "{{ host_eaas_tmp }}/eaas-image-patches.zip"
eaas_generalization_patches_tmpdir: "{{ host_eaas_tmp }}/eaas-image-patches"
eaas_generalization_patches_install_dir: "{{ host_eaas_home }}/server-data/image-generalization-patches"
eaas_generalization_patches_enabled: "{{ eaas.generalization_patches.enabled | default(false) }}"
eaas_generalization_patches_url: "{{ eaas.generalization_patches.source }}"

# workarounds for specific problems and issues
eaas_workaround_docker_hub_ratelimits: "{{ workarounds.docker_hub_ratelimits | default(false) }}"
