---
docker_custom_network: "{{ docker.custom_network | default('') }}"
docker_network_name: "{{ docker.network_name | default('') }}"

docker_compose_url: "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-Linux-x86_64"
# Checksum must match the binary and usually is located at: {{ docker_compose_url }}.sha256
docker_compose_checksum: "sha256:1cb7ecccc17c8d5f1888f9e2b3211b07e35c86d0010a6c0f711fe65ef5b69528"
docker_compose_install_path: /usr/local/bin/docker-compose
