---
- name: create temporary build-dir
  become: yes
  file:
    path: "{{ host_build_dir }}"
    state: directory
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"

- name: setup proxy/webserver
  import_tasks: webserver/setup.yaml

- name: generate custom dockerfile
  template:
    src: docker/Dockerfile.j2
    dest: "{{ host_build_dir }}/Dockerfile"

- name: pull pre-built eaas-docker image
  become: yes
  docker_image:
    force: "{{ eaas_component_docker_image in eaas_update_components }}"
    name: "{{ docker_image }}"
    state: present
    pull: yes

- name: pull pre-built proxy-docker image
  become: yes
  docker_image:
    force: "{{ eaas_component_docker_image in eaas_update_components }}"
    name: "{{ docker_proxy_image }}"
    state: present
    pull: yes

- name: build custom docker-image
  become: yes
  docker_image:
    name: "{{ docker_custom_image }}"
    path: "{{ host_build_dir }}"
    state: present
    force: yes

- name: generate docker-compose file
  template:
    src: docker/docker-compose.yaml.j2
    dest: "{{ host_eaas_home }}/docker-compose.yaml"
