---
- name: setup proxy/webserver
  import_tasks: webserver/setup.yaml

- name: pull pre-built docker image
  become: "{{ 'no' if ansible_distribution == 'MacOSX' else 'yes' }}"
  docker_image:
    force_source: "{{ eaas_component_docker_image in eaas_update_components }}"
    name: "{{ docker_image }}"
    state: present
    source: pull

- name: generate docker-compose file
  template:
    src: docker/docker-compose.yaml.j2
    dest: "{{ host_eaas_home }}/docker-compose.yaml"
