---
- name: create temporary build-dir
  become: yes
  file:
    path: "{{ host_build_dir }}"
    state: directory
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"

- name: setup proxy/webserver
  import_tasks: webserver/setup.yaml

- name: pull pre-built docker image
  become: "{{ 'no' if ansible_distribution == 'MacOSX' else 'yes' }}"
  docker_image:
    force_source: "{{ eaas_component_docker_image in eaas_update_components }}"
    name: "{{ docker_image }}"
    state: present
    build:
      pull: yes

- name: generate docker-compose file
  template:
    src: docker/docker-compose.yaml.j2
    dest: "{{ host_eaas_home }}/docker-compose.yaml"
