---
- name: enable epel repository
  become: yes
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: install common dependencies
  become: yes
  yum:
    state: present
    name:
    - python-pip
