---
- name: check supported distribution
  when: "ansible_distribution not in ['Ubuntu', 'CentOS', 'RedHat']"
  fail:
    msg: "{{ ansible_distribution }} distribution is currently not supported!"
  tags:
  - system_setup

- name: install deps on ubuntu
  when: "ansible_distribution == 'Ubuntu'"
  include_tasks: deps-ubuntu.yaml
  tags:
  - system_setup


- name: install deps on redhat/centos
  when: "ansible_distribution in ['CentOS', 'RedHat']"
  include_tasks: deps-redhat.yaml
  tags:
  - system_setup

- name: prepare temp folder
  when: host_eaas_tmp != ''
  become: yes
  file:
    path: "{{ host_eaas_tmp }}"
    state: directory
    mode: u=rwx,g=rwx,o=rwx
