---
- name: create keycloak runtime dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ keycloak_config_dir }}"
  - "{{ keycloak_secrets_dir }}"
  - "{{ keycloak_data_dir }}"
  - "{{ keycloak_theme_dir }}"

- name: prep keycloak's defaults / import
  template:
    src: keycloak/default.json.j2
    dest: "{{ keycloak_defaults_file }}"

- name: checkout keycloak's theme
  when: keycloak_theme_repo != ''
  git:
    repo: "{{ keycloak_theme_repo }}"
    dest: "{{ keycloak_theme_dir }}"

- name: prepare keycloak's admin password
  include_tasks: utils/secret.yaml
  vars:
    filepath: "{{ keycloak_secrets_dir }}/admin"
    varname: keycloak_admin_password

- name: copy keycloak's hooks
  include_tasks: utils/hook.yaml
  vars:
    kind: "{{ item.kind }}"
    name: "{{ item.name }}"
  loop:
  - kind: "post-start"
    name: "01-update-keycloak-config.sh"


- name: move keycloak's legacy data dir
  shell: |
    srcdir="{{ host_eaas_home }}/keycloak-data"
    test -e "${srcdir}" || exit 0
    mv ${srcdir}/* "{{ keycloak_data_dir }}"

- name: remove keycloak's legacy data
  file:
    path: "{{ item }}"
    state: absent
  loop:
  - "{{ host_eaas_home }}/keycloak-data"
  - "{{ host_eaas_home }}/keycloak-defaults"
  - "{{ host_eaas_home }}/theme"
