---
- name: create keycloak runtime dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ keycloak_secrets_dir }}"

- name: create keycloak data dir
  become: yes
  file:
    path: "{{ host_eaas_home }}/keycloak-data"
    state: directory
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: o+rwx 

- name: create keycloak theme dir
  become: yes
  when: keycloak_theme_repo != ''
  file:
    path: "{{ host_eaas_home }}/theme"
    state: directory
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: o+rwx 

- name: create keycloak import dir
  become: yes
  file:
    path: "{{ host_eaas_home }}/keycloak-defaults"
    state: directory
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: o+rwx 

- name: prep defaults / import
  template:
    src: keycloak/default.json.j2
    dest: "{{ host_eaas_home }}/keycloak-defaults/default.json" 

- name: checkout theme
  when: keycloak_theme_repo != ''
  become: yes
  git:
    repo: "{{ keycloak_theme_repo }}"
    dest: "{{ host_eaas_home }}/theme/"

- name: prepare keycloak's admin password
  include_tasks: utils/secret.yaml
  vars:
    filepath: "{{ keycloak_secrets_dir }}/admin"
    varname: keycloak_admin_password
