---
- name: create keycloak runtime dirs
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode | default(omit) }}"
    state: directory
  loop:
  - path: "{{ keycloak_config_dir }}"
  - path: "{{ keycloak_secrets_dir }}"
  - path: "{{ keycloak_data_dir }}"
    mode: u=rwx,g=rwx,o=rwx

- name: prep keycloak's defaults / import
  template:
    src: keycloak/default.json.j2
    dest: "{{ keycloak_defaults_file }}"

- name: download keycloak's theme
  when: keycloak_theme_enabled
  get_url:
    force: "{{ eaas_component_ui in eaas_update_components }}"
    url: "{{ keycloak_theme_url }}"
    dest: "{{ keycloak_theme_file }}"
    headers:
      PRIVATE-TOKEN: "{{ eaas_private_token  | default(omit) }}"

- name: prepare keycloak's admin password
  include_tasks: utils/secret.yaml
  vars:
    filepath: "{{ keycloak_secrets_dir }}/admin"
    varname: keycloak_admin_password

- name: copy keycloak's hooks
  include_tasks: utils/hook.yaml
  vars:
    kind: "{{ item.kind }}"
    name: "{{ item.name }}"
  loop:
  - kind: "post-start"
    name: "01-update-keycloak-config.sh"


- name: move keycloak's legacy data dir
  shell: |
    srcdir="{{ host_eaas_home }}/keycloak-data"
    test -e "${srcdir}" || exit 0
    mv ${srcdir}/* "{{ keycloak_data_dir }}"

- name: remove keycloak's legacy data
  file:
    path: "{{ item }}"
    state: absent
  loop:
  - "{{ host_eaas_home }}/keycloak-data"
  - "{{ host_eaas_home }}/keycloak-defaults"
  - "{{ host_eaas_home }}/theme"

- name: look up keycloak's image
  set_fact:
    keycloak_current_image: "{{ docker_compose_file_content.services.keycloak.image | default(omit) }}"

- name: look up keycloak's version
  set_fact:
    keycloak_current_version: "{{ keycloak_current_image.split(':')[1] | default('') }}"
