---
- name: check if docker-compose exists
  command: which docker-compose
  register: docker_compose_check
  failed_when: docker_compose_check.rc > 1

- name: download docker-compose
  when: docker_compose_check.rc != 0
  become: yes
  get_url:
    url: "{{ docker_compose_url }}"
    checksum: "{{ docker_compose_checksum }}"
    dest: "{{ docker_compose_install_path }}"
    mode: a+x

- name: update docker-compose path
  when: docker_compose_check.rc == 0
  set_fact:
    docker_compose_install_path: "{{ docker_compose_check.stdout }}"
