---
- name: install docker
  when: "unsupported_os is undefined and 'docker.service' not in ansible_facts.services"
  include_tasks: docker.yaml

- name: setup custom-network for docker
  when: docker_custom_network != ''
  include_tasks: custom-network.yaml

- name: install docker-compose
  when: "unsupported_os is undefined"
  import_tasks: docker-compose.yaml

- name: install python bindings
  become: yes
  when: "unsupported_os is undefined"
  pip:
    name:
    - requests<2.29
    - urllib3<2
    - docker
    state: present
