---
- name: create http-basic-auth file
  when: ui_http_auth != ''
  become: yes
  vars:
    workdir: /var/work
  docker_container:
    name: http-basic-auth-generator
    image: 'node:10-alpine'
    command: 'npx htpasswd -bc auth.pwd {{ ui_http_auth.user }} {{ ui_http_auth.password }}'
    cleanup: "{{ docker_cleanup | default('yes') }}"
    user: "{{ ansible_user_uid }}:{{ ansible_user_gid }}"
    working_dir: "{{ workdir }}"
    state: started
    detach: no
    env:
      HOME: /tmp
    volumes:
    - "{{ host_build_dir }}:{{ workdir }}"
