---
- name: copy custom ssl-certificate
  when: (eaas_deployment_mode != 'emucomp') and (docker_ssl_certificate != '')
  copy:
    src: "{{ item.src }}"
    dest: "{{ host_eaas_home }}/certificates/{{ item.name }}"
  loop:
  - src: "{{ docker_ssl_certificate }}"
    name: "server.crt"
  - src: "{{ docker_ssl_private_key }}"
    name: "server.key"

- name: setup http-basic-auth
  when: ui_http_auth != ''
  include_tasks: http-basic-auth.yaml

- name: setup apache webserver
  import_tasks: apache.yaml

- name: setup webproxy
  when: eaas_http_proxy != ''
  include_tasks: proxy.yaml

- name: generate dns-env
  when: (eaas_deployment_mode != 'emucomp') and (eaas_dns != '')
  template:
    src: webserver/dns-env.j2
    dest: "{{ host_eaas_config_dir }}/dns-env"
