---
- name: copy custom ssl-certificate
  when: (eaas_deployment_mode != 'emucomp') and (docker_ssl_certificate != '')
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
  loop:
  - src: "{{ docker_ssl_certificate }}"
    dst: "{{ eaas_ssl_certificate }}"
  - src: "{{ docker_ssl_private_key }}"
    dst: "{{ eaas_ssl_private_key }}"

- name: setup nginx
  when: eaas_http_proxy != ''
  include_tasks: proxy.yaml

- name: generate dns-env
  when: (eaas_deployment_mode != 'emucomp') and (eaas_dns != '')
  template:
    src: webserver/dns-env.j2
    dest: "{{ host_eaas_config_dir }}/dns-env"
